[package]
name = "yew-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.30"
reqwasm = "0.5.0"
types = { path= "../types"}
const_format="0.2.25"
lazy_static = "1.4.0"
gloo-console = "0.2.3"
gloo-utils = "0.1"
yew-router = "0.16"
js-sys = "0.3"
yew-websocket = { git = "https://github.com/security-union/yew-websocket.git", rev = "b29388a50c54c417db9cf0bf40033f62d9c616ab" }
anyhow = "1"
serde = "1"
serde_derive = "1"
protobuf = "3.2.0"

[dependencies.web-sys]
version = "0.3.58"
features = [
    "HtmlDocument",
    "console",
    "CanvasRenderingContext2d",
    "EncodedVideoChunk",
    "EncodedVideoChunkInit",
    "EncodedVideoChunkType",
    "HtmlCanvasElement",
    "HtmlImageElement",
    "Navigator",
    "MediaDevices",
    "MediaStream",
    "MediaStreamTrack",
    "MediaTrackSettings",
    "MediaStreamTrackProcessor",
    "MediaStreamTrackProcessorInit",
    "HtmlVideoElement",
    "MediaStreamConstraints",
    "ReadableStream",
    "ReadableStreamGetReaderOptions",
    "ReadableStreamDefaultReader",
    "VideoEncoder",
    "VideoEncoderInit",
    "VideoEncoderConfig",
    "VideoEncoderEncodeOptions",
    "VideoFrame",
    "VideoTrack",
    "VideoDecoder",
    "VideoDecoderConfig",
    "VideoDecoderInit",
    "LatencyMode"
]

